import { AutonomousDecision } from "./AutonomousDecision";

export class DecisionReporter {
  /**
   * Formats an autonomous resilience decision into a highly detailed, professional SRE markdown report.
   */
  public static generateMarkdownReport(decision: AutonomousDecision): string {
    const statusIcons: Record<string, string> = {
      NO_ACTION: "🟢 NO_ACTION",
      MONITOR: "🟡 MONITOR",
      RUN_EXPERIMENT: "🚀 RUN_EXPERIMENT",
      ROLLBACK: "🚨 ROLLBACK",
      PAUSE_EXPERIMENTS: "⏹️ PAUSE_EXPERIMENTS",
      REDUCE_RISK: "⚠️ REDUCE_RISK",
      ESCALATE: "🔥 ESCALATE",
      OPEN_INCIDENT: "🎫 OPEN_INCIDENT",
      REQUEST_APPROVAL: "🔒 REQUEST_APPROVAL",
    };

    const ctx = decision.context;
    const scores = ctx.enterpriseScores;
    const health = ctx.health;

    return `# 🧠 Autonomous Resilience Decision Report

## Decision Metadata
- **Decision ID**: \`${decision.id}\`
- **Timestamp**: \`${decision.timestamp}\`
- **Recommended Action**: **${statusIcons[decision.decision] || decision.decision}**
- **Evaluation Confidence**: \`${decision.confidence}%\`

---

## Executive Summary & Reasoning
${decision.reasoning}

---

## 📋 Supporting Evidence
${decision.evidence.map((ev) => `- ${ev}`).join("\n")}

---

## 📊 Supporting Telemetry & Metrics

### 🛡️ Enterprise Score Card
- **Overall Enterprise Grade**: **${scores.letterGrade}** (\`${scores.overallEnterpriseScore}/100\`)
- **Reliability Score**: \`${scores.reliabilityScore}/100\`
- **Resilience Score**: \`${scores.resilienceScore}/100\`
- **Recoverability Score**: \`${scores.recoverabilityScore}/100\`
- **Observability Score**: \`${scores.observabilityScore}/100\`
- **Operational Readiness**: \`${scores.operationalReadiness}/100\`

### 🏥 Live Platform Health State
- **Aggregate Status**: \`${health.status}\`
- **Impact Score**: \`${health.impactScore}/100\` (lower is better)
- **Active Anomalies**: ${health.activeScenarios || "None"}
- **State Description**: *${health.reason}*

### ⏳ Service Level Objectives (SLO)
- **SLO Compliance Rate**: \`${ctx.standardSlo.availability ? ctx.standardSlo.availability.actual : "N/A"}%\` (Target: \`${ctx.standardSlo.availability ? ctx.standardSlo.availability.target : "N/A"}%\`)
- **Mean Time to Recovery (MTTR)**: \`${ctx.slo.meanTimeToRecoveryMs}ms\`
- **Remaining Error Budget**: \`${ctx.standardSlo.availability ? ctx.standardSlo.availability.errorBudgetRemaining : "N/A"}%\`
- **Error Budget Consumed**: \`${ctx.standardSlo.availability ? (100 - ctx.standardSlo.availability.errorBudgetRemaining).toFixed(2) : "0"}%\`

### 📉 Regression & Baselines
- **Regression State Detected**: \`${ctx.regressionReport.isRegressed ? "⚠️ YES" : "🟢 NO"}\`
- **Stability Score Impact**: \`-${ctx.regressionReport.scoreImpact} points\`
- **Anomalies Registered**: ${ctx.regressionReport.anomalies.length > 0 ? ctx.regressionReport.anomalies.map((a) => `\`${a.metric}\` (${a.severity})`).join(", ") : "None"}

---

## 🔒 Safety & Operations Notice
*This analysis was generated by the stateless Enterprise Autonomous Resilience Engine. SRE safety guards dictate that this engine is strictly advisory and **does not execute production modifications directly**. Direct state changes are routed exclusively through audited Orchestrator pipelines.*
`;
  }

  /**
   * Formats an autonomous resilience decision into a structured, easily parsable JSON payload.
   */
  public static generateJsonReport(decision: AutonomousDecision): string {
    return JSON.stringify(
      {
        reportType: "AutonomousResilienceDecision",
        schemaVersion: "1.0.0",
        decisionId: decision.id,
        timestamp: decision.timestamp,
        recommendation: decision.decision,
        confidence: decision.confidence,
        reasoning: decision.reasoning,
        evidence: decision.evidence,
        keyMetrics: {
          overallEnterpriseScore: decision.context.enterpriseScores.overallEnterpriseScore,
          letterGrade: decision.context.enterpriseScores.letterGrade,
          platformHealthStatus: decision.context.health.status,
          healthImpactScore: decision.context.health.impactScore,
          sloAvailabilityActual: decision.context.standardSlo.availability ? decision.context.standardSlo.availability.actual : null,
          meanTimeToRecoveryMs: decision.context.slo.meanTimeToRecoveryMs,
          regressionImpactScore: decision.context.regressionReport.scoreImpact,
          isRegressed: decision.context.regressionReport.isRegressed,
          activeIncidentsCount: decision.context.incidents.filter((inc) => inc.status !== "RESOLVED").length,
        },
      },
      null,
      2
    );
  }
}
