import { ChaosExecutionContext } from "./ChaosExecutionContext";
import { ChaosExecutionResult, ExperimentRunSummary } from "./ChaosExecutionResult";

export class ChaosReporter {
  /**
   * Generates a fully compliant Markdown summary of the chaos run
   */
  public static generateMarkdownReport(context: ChaosExecutionContext, result: ChaosExecutionResult): string {
    const divider = "---";
    const runRows = result.runs
      .map(
        (run) =>
          `| ${run.name} | **${run.status.toUpperCase()}** | ${run.durationMs}ms | ${run.recovered ? "✅ Recovered" : "❌ Manual Action Needed"} | ${run.recoveryNote} |`
      )
      .join("\n");

    const logsBlock = context.logs
      .slice(-30) // Show last 30 logs
      .map((log) => `[${log.timestamp}] [${log.level.toUpperCase()}] ${log.message}`)
      .join("\n");

    return `# Dork Enterprise Chaos Experimentation Report
**Execution ID:** \`${context.executionId}\`
**Correlation ID:** \`${context.correlationId}\`
**Execution Tags:** ${context.tags.map((t) => `\`${t}\``).join(", ") || "None"}
**Status:** \`${result.overallStatus.toUpperCase()}\`

${divider}

## 1. Executive Summary
- **Overall Quality Target Met**: ${result.successRatio >= 80 ? "✅ YES" : "❌ NO"}
- **Success Ratio**: \`${result.successRatio.toFixed(1)}%\`
- **Total Experiments Tried**: \`${result.totalExecuted}\`
- **Total Automatic Rollbacks**: \`${result.rolledBackCount}\`
- **Total Duration**: \`${result.durationMs}ms\`

${divider}

## 2. Experiment Execution Matrix

| Experiment | Status | Duration | Recovery | Notes / Expected Recovery |
| :--- | :--- | :--- | :--- | :--- |
${runRows}

${divider}

## 3. Real-Time Telemetry & Logs Snapshot
\`\`\`
${logsBlock}
\`\`\`

---
*Report auto-generated by Enterprise Chaos Orchestrator on ${new Date().toUTCString()}*
`;
  }

  /**
   * Generates a fully structured JSON report suitable for dashboard components
   */
  public static generateJSONReport(context: ChaosExecutionContext, result: ChaosExecutionResult) {
    return {
      executionId: context.executionId,
      correlationId: context.correlationId,
      overallStatus: result.overallStatus,
      durationMs: result.durationMs,
      successRatio: result.successRatio,
      totalExecuted: result.totalExecuted,
      rolledBackCount: result.rolledBackCount,
      tags: context.tags,
      executionMode: context.executionMode,
      runs: result.runs,
      logs: context.logs,
      timestamp: new Date().toISOString(),
    };
  }
}
